{% set name = "pymks" %}
{% set version = "0.4" %}
{% set sha256 = "026bf6d8bdd02faad3a1cb0118bfb03389861051edb389195f047bbc5611405b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pytest
    - pytest-cov
    - nbval
    - sfepy
    - configparser  # [py27]


about:
  home: https://github.com/materialsinnovation/pymks/
  license: MIT
  license_file: 
    - LICENSE 
    - LICENSE.md 

  license_family: MIT
  summary: The Materials Knowledge System in Python
  description: |
    The Materials Knowledge Systems (MKS) is a novel data science
    approach for solving multiscale materials science problems. It
    uses techniques from physics, machine learning, regression
    analysis, signal processing, and spatial statistics to create
    processing-structure-property relationships. The MKS carries the
    potential to bridge multiple length scales using localization and
    homogenization linkages, and provides a data driven framework for
    solving inverse material design problems. The Materials Knowledge
    Materials in Python (PyMKS) framework is an object-oriented set of
    tools and examples, written in Python, that provide high-level
    access to the MKS framework for rapid creation and analysis of
    structure-property-processing relationships.
  doc_url: http://pymks.org/en/latest/rst/README.html
  dev_url: https://github.com/materialsinnovation/pymks/

extra:
  recipe-maintainers:
    - wd15
