{% set name = "pymks" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bede562d296279463e4082b46cb3e5c750781838a3e663f881f1c505cddfc403

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytest
    - numpy
    - dask
    - Deprecated
    - matplotlib-base
    - scikit-learn
    - pytest-cov
    - nbval
    - toolz
    - sfepy
    - scipy
    - pandas

test:
  imports:
    - pymks

about:
  home: https://github.com/materialsinnovation/pymks/
  license: MIT
  license_file:
    - LICENSE.md
  license_family: MIT
  summary: The Materials Knowledge System in Python
  description: |
    PyMKS is an open source, pythonic implementation of the
    methodologies developed under the aegis of Materials Knowledge
    System (MKS) to build salient process-structure-property linkages
    for materials science applications.  PyMKS provides for efficient
    tools for obtaining a digital, uniform grid representation of a
    materials internal structure in terms of its local states, and
    computing hierarchical descriptors of the structure that can be
    used to build efficient machine learning based mappings to the
    relevant response space.
  doc_url: http://pymks.org
  dev_url: https://github.com/materialsinnovation/pymks/

extra:
  recipe-maintainers:
    - wd15
