travis:
  secure:
    BINSTAR_TOKEN: aIzM/rrvCBd/4lQKZuWq82WqHPbtXaK75IcbApPlSCmHLHag6MkAfR73xhRYxjaY7komc9OFbq1M7Hjfgh+33nOAdMLlvWx3c8BJh51RvhQ7k77kRAsExKbC/tmn54HYX75ryVFJpFErTWW8p2OYrylu2lqbuJbgOF0XTvfQXhfK969UqHvc3jPSN/m3v6uFOhSLxJX6dV9m760Nhy4lT1R8Zuj/+nxzT65LIqdliM4WlTenvqmNXVQp6cWcPXUgPIypX7avgbMOD7yLWvqg8eiwtVmm8UqCARIsAAFvE7Npm0Fa2RK28FoB/sREURhAC4QgOLxxrqx9on+1QK9kceaLUGx3P2ZD6Fu9hOA+Eqo8kRakzlmrXnf+fnl1EBSTjhA00QsEUo4PsjSpv3iYd6fQSMjwgGJYrcvD08Mvm0tbJQPFguLtMcyG0qM6gfFuifpTvAinWkiv6ajHalKBgLelK5232txv/HUSQWbhC0/+TlDNG2E1EqaUG4R8Ebc5rcckkrUILjnhRBhXCx4ky3LwcvUM78jw45SDDzu/DJa7/LZuQtaXpX1ipQOMSvZt5uVKpdgIb5CxXIpUCTp9L/gUidax60qGHBHRzLhfydmgiCrxPYfzUl6PzZod6ZSj9XS7BEW8TxvKuzrS332L41ioQfQH2orymauFk15jiUY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
